import Link from 'next/link';import {notFound} from 'next/navigation';import places from '../../../data/places.json';import {Header,Footer,WhatsApp} from '../../../components/Site';
const labels={central:'Ubud & Central Bali',east:'East Bali',north:'North Bali',south:'South Bali','nusa-penida':'Nusa Penida'};
const themeText={wildlife:'wildlife',culture:'Balinese culture',nature:'nature',photography:'photography','rice-terraces':'rice terraces',waterfall:'waterfalls',swimming:'swimming',temple:'temples',spiritual:'spiritual heritage',history:'history',architecture:'architecture',village:'village life',mountain:'mountain scenery',viewpoint:'scenic viewpoints',lake:'lakes',relax:'relaxation',music:'Balinese music',craft:'local craft',workshop:'hands-on culture',performance:'traditional performance',palace:'royal heritage',garden:'gardens',beach:'beaches',coast:'coastal scenery',snorkeling:'snorkeling',diving:'diving',hiking:'walking and hiking',adventure:'adventure',sunrise:'sunrise',sunset:'sunset',surf:'surfing',food:'local dining',cave:'caves'};
const descriptions={
'besakih':'Bali’s largest and most important temple complex, set on the slopes of Mount Agung. Besakih is a major cultural anchor for an East Bali day and works especially well with Sidemen.',
'kelingking':'One of Nusa Penida’s signature viewpoints, known for its dramatic limestone headland and turquoise coast. Most day-trip itineraries focus on the clifftop viewpoint rather than the demanding descent to the beach.',
'diamond-beach':'A spectacular East Nusa Penida viewpoint with white sand, limestone cliffs and offshore rock formations. It combines naturally with Atuh Beach and nearby eastern viewpoints.',
'uluwatu-temple':'A major sea temple dramatically positioned above the Indian Ocean. It is a natural anchor for a South Bali afternoon and can be paired with nearby beaches and the Uluwatu Kecak performance.',
'ulun-danu-beratan':'An iconic lakeside temple in the cool Bedugul highlands. It is one of the strongest anchors for a North Bali route and pairs naturally with Handara, Wanagiri and nearby waterfalls.',
'sekumpul':'A dramatic waterfall destination in North Bali surrounded by steep green valleys. Because the visit involves more walking and time than a simple viewpoint stop, it is best treated as a major anchor rather than squeezed into an overloaded itinerary.',
'tegallalang':'One of the best-known rice-terrace landscapes north of Ubud. It works particularly well in a Central Bali route with Tampaksiring, temples and other nearby countryside stops.',
'monkey-forest':'A forest sanctuary in central Ubud where Balinese long-tailed macaques live among mature trees and temple structures. Its central location makes it easy to combine with other Ubud highlights.',
'tirta-empul':'A significant water temple in Tampaksiring, known for its sacred spring and purification tradition. It is a strong cultural stop for routes through northern Ubud and Central Bali.',
'lahangan-sweet':'A high viewpoint in East Bali known for expansive views toward Mount Agung and the surrounding landscape. It works best as an anchor for the Amed and Karangasem side of East Bali.',
'taman-ujung':'A former Karangasem royal water palace with pools, bridges, gardens and mountain-coast scenery. It combines well with other Karangasem highlights without requiring a rushed visit.',
'tirta-gangga':'A royal water garden in Karangasem known for pools, fountains, stone features and landscaped grounds. Its position makes it useful in several East Bali combinations.',
'lovina':'North Bali’s laid-back coastal area, best known for its black-sand shoreline and early-morning dolphin trips. A Lovina visit works best when the day is planned around the north coast rather than added to a Central Bali itinerary.',
'jatiluwih':'A broad rice-terrace landscape in Tabanan shaped by Bali’s traditional subak irrigation culture. Its scale rewards a slower visit and makes it a destination anchor rather than a quick photo stop.',
'tanah-lot':'A famous sea-temple landscape on Bali’s southwest coast, particularly popular toward sunset. It works best with western or southern Bali routes rather than East Bali combinations.'};
function intro(p){if(descriptions[p.id])return descriptions[p.id];const interests=p.themes.slice(0,3).map(x=>themeText[x]||x.replaceAll('-',' '));return `${p.name} is a ${p.anchor?'major':'worthwhile'} stop in ${p.area}, suited to travelers interested in ${interests.join(', ')}. We use its location and typical visit time when deciding whether it fits comfortably with other stops in the same Bali day.`}
function nearby(p){return places.filter(x=>x.id!==p.id&&x.region===p.region).map(x=>({...x,d:(x.lat-p.lat)**2+(x.lng-p.lng)**2})).sort((a,b)=>a.d-b.d).slice(0,4)}
export function generateStaticParams(){return places.map(p=>({slug:p.id}))}
export async function generateMetadata({params}){const {slug}=await params,p=places.find(x=>x.id===slug);if(!p)return{};return{title:`${p.name} | Bali Destination Guide`,description:`Discover ${p.name} in ${p.area}, what to expect, typical visit time and nearby places that can fit a private Bali itinerary.`,alternates:{canonical:`/destinations/${p.id}/`}}}
export default async function DestinationPage({params}){const {slug}=await params,p=places.find(x=>x.id===slug);if(!p)notFound();const close=nearby(p);return <><Header/><main><section className="page-hero destination-hero"><div className="container"><div className="breadcrumbs"><Link href="/">Home</Link> / Destinations / {labels[p.region]||p.area}</div><p className="eyebrow">{p.anchor?'MAJOR HIGHLIGHT':'BALI DESTINATION'} · {p.area}</p><h1 className="page-title">{p.name}</h1><p className="page-lead">{intro(p)}</p></div></section><div className="container tour-layout destination-layout"><article className="content"><h2>Why visit {p.name}?</h2><p>{intro(p)}</p><div className="destination-facts"><div><small>AREA</small><strong>{labels[p.region]||p.area}</strong></div><div><small>TYPICAL VISIT</small><strong>About {p.duration} minutes</strong></div><div><small>GOOD FOR</small><strong>{p.themes.slice(0,3).map(x=>themeText[x]||x).join(' · ')}</strong></div></div><h2>Plan it into your Bali day</h2><p>{p.anchor?`${p.name} works well as the main anchor of the day. Choose nearby supporting stops rather than trying to cross into another major area.`:`This stop works best as part of a route built around nearby highlights. Our planner checks distance, driving time and total visit time before suggesting a combination.`}</p><h2>Places nearby to consider</h2><div className="destination-nearby">{close.map(x=><Link key={x.id} href={`/destinations/${x.id}/`}><small>{x.area}</small><strong>{x.name}</strong><span>{x.duration} min · {x.anchor?'Major highlight':'Nearby stop'}</span></Link>)}</div><p className="destination-note">Entrance fees and operating conditions can change. We confirm the final itinerary, inclusions and price before booking.</p></article><aside className="booking"><p className="eyebrow">BUILD A PRIVATE DAY</p><div className="price">Add it to your itinerary</div><small>Choose one major area, then combine nearby places into a realistic half-day or full-day route.</small><Link className="button booking-btn" href="/build-your-trip/">Build my Bali day</Link></aside></div></main><WhatsApp/><Footer/></>}
